services:
    mc:
        image: itzg/minecraft-server
        restart: unless-stopped
        stdin_open: true
        tty: true
        ports:
            - "25565:25565"
        volumes:
            - ./data:/data
            - ./patches:/patches

        environment:
            # Java Settings
            MEMORY: 64G
            JVM_OPTS: "-Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true --add-modules=jdk.incubator.vector"
            JVM_XX_OPTS: "-XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=40 -XX:G1MaxNewSizePercent=50 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=15 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1"

            # Server Settings
            TYPE: PURPUR
            VERSION: 1.21.10
            EULA: true
            MOTD: "ยง3gem"
            ICON: "https://media.discordapp.net/stickers/1444018016495996948.webp?size=64&quality=lossless"
            ENABLE_AUTOPAUSE: true
            USE_SIMD_FLAGS: true

            # Gameplay Settings
            DIFFICULTY: normal
            MAX_PLAYERS: 64
            VIEW_DISTANCE: 16
            SIMULATION_DISTANCE: 8

            MAX_WORLD_SIZE: 10000
            ENABLE_COMMAND_BLOCK: true
            SNOOPER_ENABLED: false
            SPAWN_PROTECTION: 0
            PLAYER_IDLE_TIMEOUT: 15
            MAX_TICK_TIME: -1
            ENFORCE_SECURE_PROFILE: false
            SYNC_CHUNK_WRITES: false
            MAX_CHAINED_NEIGHBOR_UPDATES: 10000
            PATCH_DEFINITIONS: /patches

            # Addons
            DATAPACKS: |
                https://github.com/jadc/minecraft-servers/releases/download/20251212/gbg.zip
                https://github.com/jadc/minecraft-servers/releases/download/20251212/cg.zip
            REMOVE_OLD_DATAPACKS: true

            RESOURCE_PACK: https://github.com/jadc/minecraft-servers/releases/download/20251212/gbgcg.zip
            RESOURCE_PACK_SHA1: 807674a1937326bb1f4da86b28e774682f84be1b
            RESOURCE_PACK_ENFORCE: true

            PLUGINS: |
                https://github.com/KaspianDev/AntiPopup/releases/download/38def2a/AntiPopup-12.3.jar
                https://cdn.modrinth.com/data/P1OZGk5p/versions/wJ7j2lM6/ViaVersion-5.6.0.jar
